# Generated by Django 5.2.3 on 2025-07-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='file_field',
            field=models.FileField(upload_to=''),
        ),
    ]
